using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Corkboard.GitInfoGenerator;

/// <summary>
///     版本元数据源生成器：把 MSBuild 在构建时从 git 取到的 tag / 分支 / 提交号
///     编译成 <c>Corkboard.GitInfo</c> 类型，供头程序集的 <c>AssemblyInfo.cs</c> 与
///     <c>GlobalConstants</c> 读取。
/// </summary>
/// <remarks>
///     <para>
///         与上游 SecRandom 的 <c>SecRandom.SimpleGitInfoGenerator</c> 同样的接法：git 由 MSBuild target
///         执行（见仓库根 <c>GitInfo.props</c>），值通过 <c>CompilerVisibleProperty</c> 传进来；
///         生成器本身不访问文件系统，也不执行进程——源生成器里做 I/O 会让增量构建不可靠。
///     </para>
///     <para>
///         只有**头程序集**启用（<c>EnableGitInfoGenerator</c>），与上游一致：
///         类库不生成第二个公开的 GitInfo 类型，Core 通过 <c>GlobalConstants.SetVersionAssembly</c>
///         发布头程序集后来读这份元数据。
///     </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class GitInfoGenerator : IIncrementalGenerator
{
    private const string TagProperty = "build_property.CorkboardGitTag";
    private const string BranchProperty = "build_property.CorkboardGitBranch";
    private const string CommitHashProperty = "build_property.CorkboardGitCommitHash";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var values = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) =>
        {
            provider.GlobalOptions.TryGetValue(TagProperty, out var tag);
            provider.GlobalOptions.TryGetValue(BranchProperty, out var branch);
            provider.GlobalOptions.TryGetValue(CommitHashProperty, out var commitHash);

            return GitInfoValues.Create(tag, branch, commitHash);
        });

        context.RegisterSourceOutput(values, static (productionContext, value) =>
            productionContext.AddSource("Corkboard.GitInfo.g.cs", SourceText.From(Render(value), Encoding.UTF8)));
    }

    private static string Render(GitInfoValues value)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// 由 Corkboard.GitInfoGenerator 依据构建期的 git 元数据生成，请勿手工修改。");
        builder.AppendLine("namespace Corkboard;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>构建期的 git 元数据。由头程序集承载，Core 侧的 GlobalConstants 通过反射读取。</summary>");
        builder.AppendLine("public static class GitInfo");
        builder.AppendLine("{");
        AppendConstant(builder, "Tag", value.Tag);
        AppendConstant(builder, "Branch", value.Branch);
        AppendConstant(builder, "CommitHash", value.CommitHash);
        AppendConstant(builder, "AssemblyVersion", value.AssemblyVersion);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendConstant(StringBuilder builder, string name, string value) =>
        builder.Append("    public const string ").Append(name).Append(" = \"").Append(Escape(value)).AppendLine("\";");

    // netstandard2.0 没有带 StringComparison 的 Replace 重载，生成器工程目标框架就是它。
    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}

/// <summary>一次构建的 git 元数据；缺值一律退回安全默认值，绝不生成非法常量。</summary>
internal readonly struct GitInfoValues
{
    private const string Unknown = "Unknown";
    private const string FallbackTag = "0.0.0";

    public GitInfoValues(string tag, string branch, string commitHash, string assemblyVersion)
    {
        Tag = tag;
        Branch = branch;
        CommitHash = commitHash;
        AssemblyVersion = assemblyVersion;
    }

    public string Tag { get; }
    public string Branch { get; }
    public string CommitHash { get; }
    public string AssemblyVersion { get; }

    public static GitInfoValues Create(string? tag, string? branch, string? commitHash)
    {
        var normalizedTag = Normalize(tag, FallbackTag);
        return new GitInfoValues(
            normalizedTag,
            Normalize(branch, Unknown),
            Normalize(commitHash, Unknown),
            ToAssemblyVersion(normalizedTag));
    }

    private static string Normalize(string? value, string fallback)
    {
        var trimmed = value?.Trim().TrimStart('\uFEFF');
        return string.IsNullOrWhiteSpace(trimmed) ? fallback : trimmed!;
    }

    /// <summary>
    ///     把 tag 转成四段数字版本：<c>v1.2.3-beta</c> → <c>1.2.3.0</c>。
    ///     解析不出任何数字段时退回 <c>0.0.0.0</c>（合法但明显是"没版本"）。
    /// </summary>
    internal static string ToAssemblyVersion(string tag)
    {
        var segments = new List<string>();
        var current = new StringBuilder();
        var value = tag.TrimStart('v', 'V');

        foreach (var character in value)
        {
            if (char.IsDigit(character))
            {
                current.Append(character);
                continue;
            }

            if (character == '.' && current.Length > 0)
            {
                segments.Add(current.ToString());
                current.Clear();
                continue;
            }

            break;
        }

        if (current.Length > 0)
            segments.Add(current.ToString());

        if (segments.Count == 0)
            return "0.0.0.0";

        while (segments.Count < 4)
            segments.Add("0");

        if (segments.Count > 4)
            segments.RemoveRange(4, segments.Count - 4);

        for (var i = 0; i < segments.Count; i++)
        {
            if (!ushort.TryParse(segments[i], NumberStyles.None, CultureInfo.InvariantCulture, out var parsed))
                return "0.0.0.0";

            segments[i] = parsed.ToString(CultureInfo.InvariantCulture);
        }

        return string.Join(".", segments);
    }
}
