//------------------------------------------------------------------------------
// <auto-generated>
//     这段代码由 PublicResXFileCodeGenerator 生成；骨架阶段手工维护，修改 .resx 后需同步这里。
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Globalization;
using System.Resources;

namespace Corkboard.Langs.SettingsView;

/// <summary>设置窗口的页面级本地化资源。约定：每个页面/窗口一个 Langs 子目录。</summary>
public static class Resources
{
    private static ResourceManager? _resourceManager;

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("Corkboard.Langs.SettingsView.Resources", typeof(Resources).Assembly);

    public static CultureInfo? Culture { get; set; }

    public static string SettingsView_Back => ResourceManager.GetString(nameof(SettingsView_Back), Culture)!;
    public static string SettingsView_RestartRequired => ResourceManager.GetString(nameof(SettingsView_RestartRequired), Culture)!;
    public static string SettingsView_NeedsRestarting => ResourceManager.GetString(nameof(SettingsView_NeedsRestarting), Culture)!;
    public static string SettingsView_NeedsRestartingMessage => ResourceManager.GetString(nameof(SettingsView_NeedsRestartingMessage), Culture)!;
    public static string SettingsView_NeedsRestartingTooltip => ResourceManager.GetString(nameof(SettingsView_NeedsRestartingTooltip), Culture)!;
    public static string SettingsView_RestartNow => ResourceManager.GetString(nameof(SettingsView_RestartNow), Culture)!;
    public static string SettingsView_NoResult => ResourceManager.GetString(nameof(SettingsView_NoResult), Culture)!;
}
