//------------------------------------------------------------------------------
// <auto-generated>
//     这段代码由 PublicResXFileCodeGenerator 生成；骨架阶段手工维护，修改 .resx 后需同步这里。
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Globalization;
using System.Resources;

namespace Corkboard.Core.Langs.Common;

/// <summary>Core 层的公共本地化资源。</summary>
public static class Resources
{
    private static ResourceManager? _resourceManager;

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("Corkboard.Core.Langs.Common.Resources", typeof(Resources).Assembly);

    /// <summary>覆盖资源查找用的区域；启动时由 App.InitializeLanguages 写入。</summary>
    public static CultureInfo? Culture { get; set; }

    public static string App_Title => ResourceManager.GetString(nameof(App_Title), Culture)!;
    public static string Debug_DevelopmentBuild_Notice => ResourceManager.GetString(nameof(Debug_DevelopmentBuild_Notice), Culture)!;
    public static string Common_Cancel => ResourceManager.GetString(nameof(Common_Cancel), Culture)!;
    public static string Feat_Settings => ResourceManager.GetString(nameof(Feat_Settings), Culture)!;
    public static string Menu_OpenMainWindow => ResourceManager.GetString(nameof(Menu_OpenMainWindow), Culture)!;
    public static string Menu_OpenSettings => ResourceManager.GetString(nameof(Menu_OpenSettings), Culture)!;
    public static string Menu_RestartProgram => ResourceManager.GetString(nameof(Menu_RestartProgram), Culture)!;
    public static string Menu_ExitProgram => ResourceManager.GetString(nameof(Menu_ExitProgram), Culture)!;
    public static string Menu_About => ResourceManager.GetString(nameof(Menu_About), Culture)!;
    public static string MainView_LockWindow => ResourceManager.GetString(nameof(MainView_LockWindow), Culture)!;
    public static string MainView_UnlockWindow => ResourceManager.GetString(nameof(MainView_UnlockWindow), Culture)!;
    public static string Board_Title => ResourceManager.GetString(nameof(Board_Title), Culture)!;
    public static string Board_AddNote => ResourceManager.GetString(nameof(Board_AddNote), Culture)!;
    public static string Board_ConfirmAdd => ResourceManager.GetString(nameof(Board_ConfirmAdd), Culture)!;
    public static string Board_DeleteNote => ResourceManager.GetString(nameof(Board_DeleteNote), Culture)!;
    public static string Board_EditNote => ResourceManager.GetString(nameof(Board_EditNote), Culture)!;
    public static string Board_EditTitle => ResourceManager.GetString(nameof(Board_EditTitle), Culture)!;
    public static string Board_SaveEdit => ResourceManager.GetString(nameof(Board_SaveEdit), Culture)!;
    public static string Board_ReorderSubject => ResourceManager.GetString(nameof(Board_ReorderSubject), Culture)!;
    public static string Board_ResizeContent => ResourceManager.GetString(nameof(Board_ResizeContent), Culture)!;
    public static string Board_MoveSheet => ResourceManager.GetString(nameof(Board_MoveSheet), Culture)!;
    public static string Board_NoteContentPlaceholder => ResourceManager.GetString(nameof(Board_NoteContentPlaceholder), Culture)!;
    public static string Board_FontSize => ResourceManager.GetString(nameof(Board_FontSize), Culture)!;
    public static string Board_FontSizeFollowDefault => ResourceManager.GetString(nameof(Board_FontSizeFollowDefault), Culture)!;
    public static string Board_TextColor => ResourceManager.GetString(nameof(Board_TextColor), Culture)!;
    public static string Board_ClearFormat => ResourceManager.GetString(nameof(Board_ClearFormat), Culture)!;
    public static string Board_MarkdownBold => ResourceManager.GetString(nameof(Board_MarkdownBold), Culture)!;
    public static string Board_MarkdownItalic => ResourceManager.GetString(nameof(Board_MarkdownItalic), Culture)!;
    public static string Board_CustomColor => ResourceManager.GetString(nameof(Board_CustomColor), Culture)!;
    public static string Board_Preview => ResourceManager.GetString(nameof(Board_Preview), Culture)!;
    public static string Board_PreviewEmpty => ResourceManager.GetString(nameof(Board_PreviewEmpty), Culture)!;
    public static string Board_Uncategorized => ResourceManager.GetString(nameof(Board_Uncategorized), Culture)!;
    public static string Board_Untitled => ResourceManager.GetString(nameof(Board_Untitled), Culture)!;
    public static string Board_UntitledField => ResourceManager.GetString(nameof(Board_UntitledField), Culture)!;
    public static string Board_TypeLabel => ResourceManager.GetString(nameof(Board_TypeLabel), Culture)!;
    public static string Board_TypeDirect => ResourceManager.GetString(nameof(Board_TypeDirect), Culture)!;
    public static string Board_SubjectLabel => ResourceManager.GetString(nameof(Board_SubjectLabel), Culture)!;
    public static string Board_PageRangeFormat => ResourceManager.GetString(nameof(Board_PageRangeFormat), Culture)!;
    public static string Board_EmptyTitle => ResourceManager.GetString(nameof(Board_EmptyTitle), Culture)!;
    public static string Board_EmptyHint => ResourceManager.GetString(nameof(Board_EmptyHint), Culture)!;
    public static string Board_EmptyHintLocked => ResourceManager.GetString(nameof(Board_EmptyHintLocked), Culture)!;
    public static string Board_Replay => ResourceManager.GetString(nameof(Board_Replay), Culture)!;
    public static string Board_ReplayConfirm => ResourceManager.GetString(nameof(Board_ReplayConfirm), Culture)!;
    public static string Board_ReplayEmpty => ResourceManager.GetString(nameof(Board_ReplayEmpty), Culture)!;
    public static string Board_ReplayStopFormat => ResourceManager.GetString(nameof(Board_ReplayStopFormat), Culture)!;
    public static string Board_ReplayBannerFormat => ResourceManager.GetString(nameof(Board_ReplayBannerFormat), Culture)!;
    public static string Board_ReplayExit => ResourceManager.GetString(nameof(Board_ReplayExit), Culture)!;
    public static string Board_ReplayReadOnlyHint => ResourceManager.GetString(nameof(Board_ReplayReadOnlyHint), Culture)!;
    public static string Board_FieldKind_Text => ResourceManager.GetString(nameof(Board_FieldKind_Text), Culture)!;
    public static string Board_FieldKind_Paragraph => ResourceManager.GetString(nameof(Board_FieldKind_Paragraph), Culture)!;
    public static string Board_FieldKind_Number => ResourceManager.GetString(nameof(Board_FieldKind_Number), Culture)!;
    public static string Board_FieldKind_PageRange => ResourceManager.GetString(nameof(Board_FieldKind_PageRange), Culture)!;
    public static string Board_Seed_Type_Workbook => ResourceManager.GetString(nameof(Board_Seed_Type_Workbook), Culture)!;
    public static string Board_Seed_Type_Copy => ResourceManager.GetString(nameof(Board_Seed_Type_Copy), Culture)!;
    public static string Board_Seed_Type_Recite => ResourceManager.GetString(nameof(Board_Seed_Type_Recite), Culture)!;
    public static string Board_Seed_Type_Paper => ResourceManager.GetString(nameof(Board_Seed_Type_Paper), Culture)!;
    public static string Board_Seed_Field_Pages => ResourceManager.GetString(nameof(Board_Seed_Field_Pages), Culture)!;
    public static string Board_Seed_Field_Content => ResourceManager.GetString(nameof(Board_Seed_Field_Content), Culture)!;
    public static string Board_Seed_Field_Times => ResourceManager.GetString(nameof(Board_Seed_Field_Times), Culture)!;
    public static string Board_Seed_Subject_Chinese => ResourceManager.GetString(nameof(Board_Seed_Subject_Chinese), Culture)!;
    public static string Board_Seed_Subject_Math => ResourceManager.GetString(nameof(Board_Seed_Subject_Math), Culture)!;
    public static string Board_Seed_Subject_English => ResourceManager.GetString(nameof(Board_Seed_Subject_English), Culture)!;
    public static string Board_Layout_SingleColumn => ResourceManager.GetString(nameof(Board_Layout_SingleColumn), Culture)!;
    public static string Board_Layout_Block => ResourceManager.GetString(nameof(Board_Layout_Block), Culture)!;
    public static string Board_Layout_Flow => ResourceManager.GetString(nameof(Board_Layout_Flow), Culture)!;
    public static string Board_DeleteConfirmTitle => ResourceManager.GetString(nameof(Board_DeleteConfirmTitle), Culture)!;
    public static string Board_DeleteConfirmMessage => ResourceManager.GetString(nameof(Board_DeleteConfirmMessage), Culture)!;
    public static string Settings_Title => ResourceManager.GetString(nameof(Settings_Title), Culture)!;
    public static string Settings_Group_General => ResourceManager.GetString(nameof(Settings_Group_General), Culture)!;
    public static string Settings_Group_About => ResourceManager.GetString(nameof(Settings_Group_About), Culture)!;
    public static string Settings_Basic_Title => ResourceManager.GetString(nameof(Settings_Basic_Title), Culture)!;
    public static string Settings_Basic_Language => ResourceManager.GetString(nameof(Settings_Basic_Language), Culture)!;
    public static string Settings_Basic_Language_ChineseSimplified => ResourceManager.GetString(nameof(Settings_Basic_Language_ChineseSimplified), Culture)!;
    public static string Settings_Basic_Language_English => ResourceManager.GetString(nameof(Settings_Basic_Language_English), Culture)!;
    public static string Settings_DesktopIntegrationFailed => ResourceManager.GetString(nameof(Settings_DesktopIntegrationFailed), Culture)!;
    public static string Settings_Basic_Autostart => ResourceManager.GetString(nameof(Settings_Basic_Autostart), Culture)!;
    public static string Settings_Basic_AutostartDescription => ResourceManager.GetString(nameof(Settings_Basic_AutostartDescription), Culture)!;
    public static string Settings_Basic_ShowStartupWindow => ResourceManager.GetString(nameof(Settings_Basic_ShowStartupWindow), Culture)!;
    public static string Settings_Basic_ShowStartupWindowDescription => ResourceManager.GetString(nameof(Settings_Basic_ShowStartupWindowDescription), Culture)!;
    public static string Settings_Basic_AutoSaveWindowSize => ResourceManager.GetString(nameof(Settings_Basic_AutoSaveWindowSize), Culture)!;
    public static string Settings_Basic_AutoSaveWindowSizeDescription => ResourceManager.GetString(nameof(Settings_Basic_AutoSaveWindowSizeDescription), Culture)!;
    public static string Settings_Basic_PinToDesktop => ResourceManager.GetString(nameof(Settings_Basic_PinToDesktop), Culture)!;
    public static string Settings_Basic_PinToDesktopDescription => ResourceManager.GetString(nameof(Settings_Basic_PinToDesktopDescription), Culture)!;
    public static string Settings_Basic_HoldToDragWindow => ResourceManager.GetString(nameof(Settings_Basic_HoldToDragWindow), Culture)!;
    public static string Settings_Basic_HoldToDragWindowDescription => ResourceManager.GetString(nameof(Settings_Basic_HoldToDragWindowDescription), Culture)!;
    public static string Settings_Basic_MainWindowOpacity => ResourceManager.GetString(nameof(Settings_Basic_MainWindowOpacity), Culture)!;
    public static string Settings_Basic_MainWindowOpacityDescription => ResourceManager.GetString(nameof(Settings_Basic_MainWindowOpacityDescription), Culture)!;
    public static string Settings_Basic_ClickThrough => ResourceManager.GetString(nameof(Settings_Basic_ClickThrough), Culture)!;
    public static string Settings_Basic_ClickThroughDescription => ResourceManager.GetString(nameof(Settings_Basic_ClickThroughDescription), Culture)!;
    public static string Settings_Group_Board => ResourceManager.GetString(nameof(Settings_Group_Board), Culture)!;
    public static string Settings_Board_Title => ResourceManager.GetString(nameof(Settings_Board_Title), Culture)!;
    public static string Settings_Board_Name => ResourceManager.GetString(nameof(Settings_Board_Name), Culture)!;
    public static string Settings_Board_NamePlaceholder => ResourceManager.GetString(nameof(Settings_Board_NamePlaceholder), Culture)!;
    public static string Settings_Board_Layout => ResourceManager.GetString(nameof(Settings_Board_Layout), Culture)!;
    public static string Settings_Board_LayoutDescription => ResourceManager.GetString(nameof(Settings_Board_LayoutDescription), Culture)!;
    public static string Settings_Board_SortMode => ResourceManager.GetString(nameof(Settings_Board_SortMode), Culture)!;
    public static string Settings_Board_Sort_CreatedDescending => ResourceManager.GetString(nameof(Settings_Board_Sort_CreatedDescending), Culture)!;
    public static string Settings_Board_Sort_CreatedAscending => ResourceManager.GetString(nameof(Settings_Board_Sort_CreatedAscending), Culture)!;
    public static string Settings_Board_Sort_UpdatedDescending => ResourceManager.GetString(nameof(Settings_Board_Sort_UpdatedDescending), Culture)!;
    public static string Settings_Board_Sort_Subject => ResourceManager.GetString(nameof(Settings_Board_Sort_Subject), Culture)!;
    public static string Settings_Board_Sort_Manual => ResourceManager.GetString(nameof(Settings_Board_Sort_Manual), Culture)!;
    public static string Settings_Board_ConfirmBeforeDelete => ResourceManager.GetString(nameof(Settings_Board_ConfirmBeforeDelete), Culture)!;
    public static string Settings_Board_Subjects => ResourceManager.GetString(nameof(Settings_Board_Subjects), Culture)!;
    public static string Settings_Board_SubjectsDescription => ResourceManager.GetString(nameof(Settings_Board_SubjectsDescription), Culture)!;
    public static string Settings_Board_Types => ResourceManager.GetString(nameof(Settings_Board_Types), Culture)!;
    public static string Settings_Board_TypesDescription => ResourceManager.GetString(nameof(Settings_Board_TypesDescription), Culture)!;
    public static string Settings_Board_TypeAdd => ResourceManager.GetString(nameof(Settings_Board_TypeAdd), Culture)!;
    public static string Settings_Board_TypeDelete => ResourceManager.GetString(nameof(Settings_Board_TypeDelete), Culture)!;
    public static string Settings_Board_TypeDeleteMessage => ResourceManager.GetString(nameof(Settings_Board_TypeDeleteMessage), Culture)!;
    public static string Settings_Board_TypeNamePlaceholder => ResourceManager.GetString(nameof(Settings_Board_TypeNamePlaceholder), Culture)!;
    public static string Settings_Board_TypeFieldAdd => ResourceManager.GetString(nameof(Settings_Board_TypeFieldAdd), Culture)!;
    public static string Settings_Board_FieldLabelPlaceholder => ResourceManager.GetString(nameof(Settings_Board_FieldLabelPlaceholder), Culture)!;
    public static string Settings_Board_FieldKind => ResourceManager.GetString(nameof(Settings_Board_FieldKind), Culture)!;
    public static string Settings_Board_FieldDelete => ResourceManager.GetString(nameof(Settings_Board_FieldDelete), Culture)!;
    public static string Settings_Board_ContentStyle => ResourceManager.GetString(nameof(Settings_Board_ContentStyle), Culture)!;
    public static string Settings_Board_ContentStyleDescription => ResourceManager.GetString(nameof(Settings_Board_ContentStyleDescription), Culture)!;
    public static string Settings_Board_DefaultFontSize => ResourceManager.GetString(nameof(Settings_Board_DefaultFontSize), Culture)!;
    public static string Settings_Board_DefaultColor => ResourceManager.GetString(nameof(Settings_Board_DefaultColor), Culture)!;
    public static string Settings_Board_DefaultColorFollowTheme => ResourceManager.GetString(nameof(Settings_Board_DefaultColorFollowTheme), Culture)!;
    public static string Settings_Board_Palette => ResourceManager.GetString(nameof(Settings_Board_Palette), Culture)!;
    public static string Settings_Board_PaletteDescription => ResourceManager.GetString(nameof(Settings_Board_PaletteDescription), Culture)!;
    public static string Settings_Board_PaletteAdd => ResourceManager.GetString(nameof(Settings_Board_PaletteAdd), Culture)!;
    public static string Settings_Board_PaletteDelete => ResourceManager.GetString(nameof(Settings_Board_PaletteDelete), Culture)!;
    public static string Settings_Board_PaletteMoveUp => ResourceManager.GetString(nameof(Settings_Board_PaletteMoveUp), Culture)!;
    public static string Settings_Board_PaletteMoveDown => ResourceManager.GetString(nameof(Settings_Board_PaletteMoveDown), Culture)!;
    public static string Settings_Group_Personalized => ResourceManager.GetString(nameof(Settings_Group_Personalized), Culture)!;
    public static string Settings_Appearance_Title => ResourceManager.GetString(nameof(Settings_Appearance_Title), Culture)!;
    public static string Settings_Appearance_Theme => ResourceManager.GetString(nameof(Settings_Appearance_Theme), Culture)!;
    public static string Settings_Appearance_ThemeDescription => ResourceManager.GetString(nameof(Settings_Appearance_ThemeDescription), Culture)!;
    public static string Settings_Appearance_Theme_FollowSystem => ResourceManager.GetString(nameof(Settings_Appearance_Theme_FollowSystem), Culture)!;
    public static string Settings_Appearance_Theme_Light => ResourceManager.GetString(nameof(Settings_Appearance_Theme_Light), Culture)!;
    public static string Settings_Appearance_Theme_Dark => ResourceManager.GetString(nameof(Settings_Appearance_Theme_Dark), Culture)!;
    public static string Settings_Appearance_ThemeColor => ResourceManager.GetString(nameof(Settings_Appearance_ThemeColor), Culture)!;
    public static string Settings_Appearance_ThemeColorDescription => ResourceManager.GetString(nameof(Settings_Appearance_ThemeColorDescription), Culture)!;
    public static string Settings_Appearance_ThemeColorMode_Default => ResourceManager.GetString(nameof(Settings_Appearance_ThemeColorMode_Default), Culture)!;
    public static string Settings_Appearance_ThemeColorMode_Custom => ResourceManager.GetString(nameof(Settings_Appearance_ThemeColorMode_Custom), Culture)!;
    public static string Settings_Appearance_FontFamily => ResourceManager.GetString(nameof(Settings_Appearance_FontFamily), Culture)!;
    public static string Settings_Appearance_FontFamilyDescription => ResourceManager.GetString(nameof(Settings_Appearance_FontFamilyDescription), Culture)!;
    public static string Settings_Appearance_FontFamilyDefault => ResourceManager.GetString(nameof(Settings_Appearance_FontFamilyDefault), Culture)!;
    public static string Settings_Appearance_FontWeight => ResourceManager.GetString(nameof(Settings_Appearance_FontWeight), Culture)!;
    public static string Settings_Appearance_FontWeightDescription => ResourceManager.GetString(nameof(Settings_Appearance_FontWeightDescription), Culture)!;
    public static string Settings_Appearance_FontWeight_Thin => ResourceManager.GetString(nameof(Settings_Appearance_FontWeight_Thin), Culture)!;
    public static string Settings_Appearance_FontWeight_ExtraLight => ResourceManager.GetString(nameof(Settings_Appearance_FontWeight_ExtraLight), Culture)!;
    public static string Settings_Appearance_FontWeight_Light => ResourceManager.GetString(nameof(Settings_Appearance_FontWeight_Light), Culture)!;
    public static string Settings_Appearance_FontWeight_Normal => ResourceManager.GetString(nameof(Settings_Appearance_FontWeight_Normal), Culture)!;
    public static string Settings_Appearance_FontWeight_Medium => ResourceManager.GetString(nameof(Settings_Appearance_FontWeight_Medium), Culture)!;
    public static string Settings_Appearance_FontWeight_SemiBold => ResourceManager.GetString(nameof(Settings_Appearance_FontWeight_SemiBold), Culture)!;
    public static string Settings_Appearance_FontWeight_Bold => ResourceManager.GetString(nameof(Settings_Appearance_FontWeight_Bold), Culture)!;
    public static string Settings_Appearance_FontWeight_ExtraBold => ResourceManager.GetString(nameof(Settings_Appearance_FontWeight_ExtraBold), Culture)!;
    public static string Settings_Appearance_FontWeight_Black => ResourceManager.GetString(nameof(Settings_Appearance_FontWeight_Black), Culture)!;
    public static string Settings_About_Title => ResourceManager.GetString(nameof(Settings_About_Title), Culture)!;
    public static string Settings_About_Version => ResourceManager.GetString(nameof(Settings_About_Version), Culture)!;
    public static string Settings_About_License => ResourceManager.GetString(nameof(Settings_About_License), Culture)!;
}
