//------------------------------------------------------------------------------
// <auto-generated>
//     这段代码由 PublicResXFileCodeGenerator 生成；骨架阶段手工维护，修改 .resx 后需同步这里。
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Globalization;
using System.Resources;

namespace Corkboard.Core.Langs.Common;

/// <summary>Core 层的公共本地化资源。</summary>
public static class Resources
{
    private static ResourceManager? _resourceManager;

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("Corkboard.Core.Langs.Common.Resources", typeof(Resources).Assembly);

    /// <summary>覆盖资源查找用的区域；启动时由 App.InitializeLanguages 写入。</summary>
    public static CultureInfo? Culture { get; set; }

    public static string App_Title => ResourceManager.GetString(nameof(App_Title), Culture)!;
    public static string Feat_Settings => ResourceManager.GetString(nameof(Feat_Settings), Culture)!;
    public static string Menu_OpenMainWindow => ResourceManager.GetString(nameof(Menu_OpenMainWindow), Culture)!;
    public static string Menu_OpenSettings => ResourceManager.GetString(nameof(Menu_OpenSettings), Culture)!;
    public static string Menu_RestartProgram => ResourceManager.GetString(nameof(Menu_RestartProgram), Culture)!;
    public static string Menu_ExitProgram => ResourceManager.GetString(nameof(Menu_ExitProgram), Culture)!;
    public static string Menu_About => ResourceManager.GetString(nameof(Menu_About), Culture)!;
    public static string Board_AddNote => ResourceManager.GetString(nameof(Board_AddNote), Culture)!;
    public static string Board_Title => ResourceManager.GetString(nameof(Board_Title), Culture)!;
    public static string Board_DeleteNote => ResourceManager.GetString(nameof(Board_DeleteNote), Culture)!;
    public static string Board_PinNote => ResourceManager.GetString(nameof(Board_PinNote), Culture)!;
    public static string Board_EmptyTitle => ResourceManager.GetString(nameof(Board_EmptyTitle), Culture)!;
    public static string Board_EmptyHint => ResourceManager.GetString(nameof(Board_EmptyHint), Culture)!;
    public static string Board_NoteTitlePlaceholder => ResourceManager.GetString(nameof(Board_NoteTitlePlaceholder), Culture)!;
    public static string Board_NoteContentPlaceholder => ResourceManager.GetString(nameof(Board_NoteContentPlaceholder), Culture)!;
    public static string Settings_Title => ResourceManager.GetString(nameof(Settings_Title), Culture)!;
    public static string Settings_Group_General => ResourceManager.GetString(nameof(Settings_Group_General), Culture)!;
    public static string Settings_Group_About => ResourceManager.GetString(nameof(Settings_Group_About), Culture)!;
    public static string Settings_Basic_Title => ResourceManager.GetString(nameof(Settings_Basic_Title), Culture)!;
    public static string Settings_Basic_Language => ResourceManager.GetString(nameof(Settings_Basic_Language), Culture)!;
    public static string Settings_Basic_ShowStartupWindow => ResourceManager.GetString(nameof(Settings_Basic_ShowStartupWindow), Culture)!;
    public static string Settings_Basic_BackgroundResident => ResourceManager.GetString(nameof(Settings_Basic_BackgroundResident), Culture)!;
    public static string Settings_Basic_AutoSaveWindowSize => ResourceManager.GetString(nameof(Settings_Basic_AutoSaveWindowSize), Culture)!;
    public static string Settings_About_Title => ResourceManager.GetString(nameof(Settings_About_Title), Culture)!;
    public static string Settings_About_Version => ResourceManager.GetString(nameof(Settings_About_Version), Culture)!;
    public static string Settings_About_License => ResourceManager.GetString(nameof(Settings_About_License), Culture)!;
}
